# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "github-actions", "redisv8" ]
  pull_request:
    branches: [ "master", "redisv8" ]
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install redis cluster service
        uses: pfapi/redis-cluster-service@v1

      - name: start redis cluster
        run: sudo systemctl start redis-cluster

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
